using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace region_ders30_kodu_gizlemek
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            #region
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty; label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            label1.Text = string.Empty;
            #endregion
        }
    }
}
